### ISSUE TITLE
Could not fetch data auth token

### ISSUE THREAD

**Issue by storigen** [tomzx/imdb-importer#9]
I am unable to use the ID token, did something change in the way IMDB does this?I opened a new dummy account to test this, here is my id string for it:

`$id = 'BCYsd4ueL5NUziS1nwLRSmvusCHXjrt2rlyRKRTd5ueh5akqJDFFilYcqguokk1e-oLDijbLcMRh%0D%0AUSQxfzvWFqIneuUq5Ri29A8wQwB4qH6nLDObCIxqs_mjeqL262BwMpFymt6Lqi2I0suv-dGnpe9n%0D%0AFQ%0D%0A';`

However, when I run the code, it starts searching for the first movie, then crashes, see below
**"Could not fetch data auth token."**

```
C:\Projects\TraktSync\imdb-importer\>php runme.php

Searching for Jurassic Park
PHP Fatal error:  Uncaught Exception: Could not fetch data auth token. in C:\Projects\TraktSync\imdb-importer\src\ImdbImporter\Importer.php:189
Stack trace:
#0 C:\Projects\TraktSync\imdb-importer\src\ImdbImporter\Importer.php(70): ImdbImporter\Importer->getAuthToken('tt0107290')
#1 C:\Projects\TraktSync\imdb-importer\runme.php(12): ImdbImporter\Importer->submit(Array)
#2 {main} thrown in C:\Projects\TraktSync\imdb-importer\src\ImdbImporter\Importer.php on line 189
```

**Comment by tomzx** [comment]
It appears that changes in IMDB have occurred which currently breaks the existing implementation.

I did an initial assessment and it appears that they've added a `sid` cookie which appears to be very similar to the `id` cookie. However, having both will still lead to issues once it's time to submit the ratings as it will return a 400 Bad request.

My tests through Chrome seem to indicate that providing only those two cookies should work, but when I try to reproduce this the existing code, I'm getting 400, even after trying to add the `x-imdb-parent-id` header. I'll try to look into this again when I have an idea of what might be wrong/missing.
